---
# Lookup table to map between Ansible architectures and Punchr release
# architectures. Key is Ansible, value is Punchr.
arch_table:
  x86_64: "amd64"
  x86: "386"
  aarch64: "arm64"
  armv7l: "arm7"

punchr_enabled: false
punchr_ver: "v0.9.0"
punchr_user: "nobody"
punchr_base: "/usr/local"
punchr_home: "/var/run/punchr"
punchr_bin: "punchr_cli_{{ ansible_system | lower }}_{{ arch_table[ansible_architecture] }}"
punchr_uri: "https://github.com/dennis-tra/punchr/releases/download/{{ punchr_ver }}/{{ punchr_bin }}"
